export const AVAILABLE_TAGS = [
  "Array",
  "String",
  "Hash Table",
  "Math",
  "Dynamic Programming",
  "Sorting",
  "Greedy",
  "Depth-First Search",
  "Binary Search",
  "Breadth-First Search",
  "Tree",
  "Matrix",
  "Two Pointers",
  "Bit Manipulation",
  "Stack",
  "Heap (Priority Queue)",
  "Graph",
  "Backtracking",
  "Linked List",
  "Trie",
  "Union Find",
  "Recursion"
];